### ISSUE TITLE
Support RESTful API documentation

### ISSUE THREAD

**Issue by vzzederzv** [trinitytechnology/ebrick#14]
The Framework should have an option to enable API documentation for RESTful Route handlers that exist in the application.
Some aspects need consideration:
1. Whether to enable API docs generation for any specific module or all modules.
2. Whether to generate API docs on the application booting-up phase or run a specific command line to trigger.
3. Whether to automatically generate API docs by source code analysis or using [Gin Swagger](https://github.com/swaggo/gin-swagger) and [Swaggo](https://github.com/swaggo/swag) with user manually inputted [General API Info Comment](https://github.com/swaggo/swag?tab=readme-ov-file#general-api-info)

**Comment by thanhtrinity** [comment]
@vzzederzv  this ticket is related to #2 ?

**Comment by vzzederzv** [comment]
Move to #2 as duplicated.

**Comment by vzzederzv** [comment]
Move to https://github.com/trinitytechnology/ebrick/issues/2 as duplicated.

**Comment by vzzederzv** [comment]
Move to https://github.com/trinitytechnology/ebrick/issues/2 as duplicated.
